name: rizzbot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase and Google Sign-In
  firebase_core: ^2.27.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.18.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  google_generative_ai: ^0.4.7
  shared_preferences: ^2.2.3
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.2  # Added for image uploading
  image_picker: ^1.1.2      # Added for image selection

  
  # Other packages
  http: ^1.2.1
  tesseract_ocr: 0.5.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
