name: rizzbot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase and Google Sign-In
  firebase_core: ^2.27.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.18.0
  google_fonts: ^6.3.1
  animated_text_kit: ^4.2.2
  google_generative_ai: ^0.4.7
  shared_preferences: ^2.5.3
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.2  # Added for image uploading
  image_picker: ^1.1.2      # Added for image selection

  
  # Other packages
  tesseract_ocr: 0.5.0
  font_awesome_flutter: ^10.7.0
  flutter_dotenv: ^5.1.0
  provider: ^6.1.5+1
  cached_network_image: ^3.3.1
  flutter_speed_dial: ^7.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - .env